# Generated by Django 5.2 on 2025-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_lawyer_notified',
            field=models.BooleanField(default=False),
        ),
    ]
