# Generated by Django 5.1.7 on 2025-04-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0002_alter_lawyer_managers_lawyer_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
