# Generated by Django 5.2 on 2025-05-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0002_consultation_is_client_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='message_from_lawyer',
            field=models.TextField(blank=True, help_text='Message or instructions from the lawyer', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for the consultation', null=True),
        ),
    ]
