# Generated by Django 5.1.7 on 2025-04-05 06:11

import consultation_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0003_lawyer_profile_picture_alter_lawyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='specialization',
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('education', models.TextField()),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=consultation_app.models.upload_to_profile)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
