# Generated by Django 5.2 on 2025-05-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_message_file'),
        ('consultation_app', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='ChatApp.room'),
        ),
    ]
