# Generated by Django 5.2 on 2025-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0006_consultation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client_in_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lawyer_in_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='video_session_active',
            field=models.BooleanField(default=False, help_text='Whether video call is currently active'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='video_session_ended_at',
            field=models.DateTimeField(blank=True, help_text='When video call ended', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='video_session_room_id',
            field=models.CharField(blank=True, help_text='Unique room ID for video call', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='video_session_started_at',
            field=models.DateTimeField(blank=True, help_text='When video call started', null=True),
        ),
    ]
