# Generated by Django 5.2 on 2025-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0006_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
