# Generated by Django 5.2 on 2025-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0007_lawyer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='professional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='lawyer_certificates/'),
        ),
    ]
