# Generated by Django 5.2 on 2025-06-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0007_consultation_client_in_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='client_in_video',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='lawyer_in_video',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='video_session_active',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='video_session_ended_at',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='video_session_room_id',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='video_session_started_at',
        ),
    ]
