# Generated by Django 5.2 on 2025-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0008_lawyerprofile_professional_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_profiles/'),
        ),
    ]
