# Generated by Django 5.2 on 2025-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0009_alter_lawyerprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='legal_news_images/')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LegalNews',
        ),
    ]
