# Generated by Django 5.2 on 2025-06-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0009_videocall'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocall',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_app.consultation'),
        ),
    ]
