# Generated by Django 5.2 on 2025-06-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_app', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
