# Generated by Django 5.2 on 2025-06-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_object_id',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatApp.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
